configure.ac: parse python LDFLAGS
At least on Windows, python bindings produce lots of linkedit
errors, like:

	D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: python/.libs/zbar_la-zbarmodule.o: in function `Py_DECREF':
	D:/a/_temp/msys/msys64/mingw32/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
	D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: python/.libs/zbar_la-zbarmodule.o: in function `increase_verbosity':
	D:\a\zbar\zbar/python/zbarmodule.c:173: undefined reference to `PyArg_ParseTuple'

That's probably because the python libraries were not included.

So, add a LDFLAGS to configure.

Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>